---
apiVersion: v1
kind: Namespace
metadata:
    name: rcms
    labels:
        dept: it

---
apiVersion: v1
kind: Pod
metadata:
    name: rcms-web-server
    namespace: rcms
    labels:
        client: axis
        app: axis-web
spec:
    containers:
        - name: axis-container
          image: rcms/axis:v4
          ports:
              - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: axis-Service
    namespace: rcms
    labels:
        client: axis
spec:
    type: NodePort
    selector:
        app: axis-web
    ports:
        - port: 80
          nodePort: 8080
